//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaKhuyenMai
    {
        public int IDMaKM { get; set; }
        public string MaKM { get; set; }
        public string TenKM { get; set; }
        public Nullable<decimal> GiaTriKM { get; set; }
    }
}
